name: dynamic-test-matrix

on:
  workflow_dispatch:

jobs:
  matrix:
    name: Generate test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix-json: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        shell: bash
        # Use a small PowerShell script to generate the test matrix
        run: python set_matrix.py

  run-matrix:
    needs: [matrix]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.matrix-json) }}
    name: create with matrix
    runs-on: ubuntu-latest
    steps:
      - name: create notifications
        id: derp
        uses: ogie-gh/derp/notifications@main
        with:
         prefix: "${{ matrix.prefix }}"
         summary: "${{ matrix.summary }}"
         description: "${{ matrix.description }}"
